### ISSUE TITLE
5.6.6 support?

### ISSUE THREAD

**Issue by twobob** [Roland09/Environment#2]
You don't list a supported Unity version.

I'm gonna try hacking the prefab brush to be useful since Physics.simulate is only available in a closed 5.6.4 beta... then 2017.2

Other than that thing this seems version agnostic so far

**Comment by twobob** [comment]
Yeah. you can just elide out the simulation stuff and it still works fine on 5.6.6

**Comment by Roland09** [comment]
Thanks, gonna add the version to the readme. I don't see a point in supporting anything before 2018 for this hobby project :-) I'm closing this issue since I moved the asset to a new dedicated repository:

https://github.com/Roland09/PrefabPainter
